spring:
  application:
    name: event-pipeline
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 메시지 브로커 선택: nats / spring-event
messaging:
  broker: nats

nats:
  url: nats://localhost:4222
  subject: events.api.call

event:
  generator:
    enabled: true
    interval-ms: 500
    weights:
      success: 70
      client-error: 15
      server-error: 5
      slow: 10
